/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsEdukidsRouteImport } from './routes/projects.edukids'
import { Route as ProjectsChenethaerpRouteImport } from './routes/projects.chenethaerp'
import { Route as ProjectsChenethaWebRouteImport } from './routes/projects.chenetha-web'
import { Route as ProjectsBrandPlatformRouteImport } from './routes/projects.brand-platform'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEdukidsRoute = ProjectsEdukidsRouteImport.update({
  id: '/projects/edukids',
  path: '/projects/edukids',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsChenethaerpRoute = ProjectsChenethaerpRouteImport.update({
  id: '/projects/chenethaerp',
  path: '/projects/chenethaerp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsChenethaWebRoute = ProjectsChenethaWebRouteImport.update({
  id: '/projects/chenetha-web',
  path: '/projects/chenetha-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBrandPlatformRoute = ProjectsBrandPlatformRouteImport.update({
  id: '/projects/brand-platform',
  path: '/projects/brand-platform',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/brand-platform': typeof ProjectsBrandPlatformRoute
  '/projects/chenetha-web': typeof ProjectsChenethaWebRoute
  '/projects/chenethaerp': typeof ProjectsChenethaerpRoute
  '/projects/edukids': typeof ProjectsEdukidsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/brand-platform': typeof ProjectsBrandPlatformRoute
  '/projects/chenetha-web': typeof ProjectsChenethaWebRoute
  '/projects/chenethaerp': typeof ProjectsChenethaerpRoute
  '/projects/edukids': typeof ProjectsEdukidsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/brand-platform': typeof ProjectsBrandPlatformRoute
  '/projects/chenetha-web': typeof ProjectsChenethaWebRoute
  '/projects/chenethaerp': typeof ProjectsChenethaerpRoute
  '/projects/edukids': typeof ProjectsEdukidsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/brand-platform'
    | '/projects/chenetha-web'
    | '/projects/chenethaerp'
    | '/projects/edukids'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/brand-platform'
    | '/projects/chenetha-web'
    | '/projects/chenethaerp'
    | '/projects/edukids'
  id:
    | '__root__'
    | '/'
    | '/projects/brand-platform'
    | '/projects/chenetha-web'
    | '/projects/chenethaerp'
    | '/projects/edukids'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsBrandPlatformRoute: typeof ProjectsBrandPlatformRoute
  ProjectsChenethaWebRoute: typeof ProjectsChenethaWebRoute
  ProjectsChenethaerpRoute: typeof ProjectsChenethaerpRoute
  ProjectsEdukidsRoute: typeof ProjectsEdukidsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/edukids': {
      id: '/projects/edukids'
      path: '/projects/edukids'
      fullPath: '/projects/edukids'
      preLoaderRoute: typeof ProjectsEdukidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/chenethaerp': {
      id: '/projects/chenethaerp'
      path: '/projects/chenethaerp'
      fullPath: '/projects/chenethaerp'
      preLoaderRoute: typeof ProjectsChenethaerpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/chenetha-web': {
      id: '/projects/chenetha-web'
      path: '/projects/chenetha-web'
      fullPath: '/projects/chenetha-web'
      preLoaderRoute: typeof ProjectsChenethaWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/brand-platform': {
      id: '/projects/brand-platform'
      path: '/projects/brand-platform'
      fullPath: '/projects/brand-platform'
      preLoaderRoute: typeof ProjectsBrandPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsBrandPlatformRoute: ProjectsBrandPlatformRoute,
  ProjectsChenethaWebRoute: ProjectsChenethaWebRoute,
  ProjectsChenethaerpRoute: ProjectsChenethaerpRoute,
  ProjectsEdukidsRoute: ProjectsEdukidsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
